version: '3.7'
services:
  web:
    container_name: ctr-book-board
    build:
      context: .
    image: img-book-board
    volumes:
      - .:/usr/src/app
      - ~/.config/configstore:/root/.”config/configstore
      - ~/.local:/root/.local
    ports:
      - 3000:3000
    command:
      - ./cmd.sh